version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/infratest"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

---

# GitHub Actions CI/CD Pipeline

name: Deploy Infrastructure Testing App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/infra-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/infra-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/infra-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/infra-frontend:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/infra-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/infra-frontend:latest
            docker-compose up -d

      - name: Cleanup old Docker images
        run: |
          docker system prune -af
