name: Terraform Provisioning CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"

      - name: Terraform Apply (Auto-Approve)
        run: |
          terraform apply -auto-approve tfplan \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"

      - name: Cleanup Terraform Artifacts
        run: rm -f tfplan